version: '3'

networks:
  default:
    driver: bridge

services:
  php:
    image: yiisoftware/yii2-php:8.1-fpm
    networks:
      - default
    ports:
      - ':9000'
    depends_on:
      - db
    volumes:
      - "./:/var/www/html"
      - "./deploy/php/:/usr/local/etc/php"




  nginx:
    networks:
      - default

    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './:/var/www/html'
      - './deploy/nginx:/etc/nginx/conf.d'
    links:
      - php





  db:
    image: mysql:latest
    # Подключаем к общей сети с другими контейнерами
    networks:
      - default
    # Показываем наружу порт
    ports:
      - "3336:3306"
    # Задаем параметры для инициализации БД
    environment:
      # Пароль к БД
      MYSQL_ROOT_PASSWORD: root
      # Создаваемая по умолчанию бд
      MYSQL_DATABASE: taskforce
      MYSQL_ROOT_USER: root
    # Линкуем внешнюю папку для хранения БД
    volumes:
      - taskforcedata:/var/lib/mysql
volumes:
  taskforcedata:
